### ISSUE TITLE
Homebrew GitHub API token

### ISSUE THREAD

**Issue by sdushantha** [eyedol/tools#2]
Hey,

I just wanted to let you know that I found your `HOMEBREW_GITHUB_API_TOKEN` in the [mac-zshrc](https://github.com/eyedol/tools/blob/85a6875b2da81035dce9a4d3471944bf657dbc1a/mac-zshrc#L73) file and I doubt that you want that to be public.

**Comment by eyedol** [comment]
Fix with 734fd74348b22aa11d05b6f6ea924b3a47a9809d now uses git-encrypt to encrypt all files. Thanks for reporting it.
